apiVersion: v2
name: umbrella
version: 1.0.0
appVersion: 1.0.0
description: My umbrella chart
type: application

dependencies:
  - name: service-1
    version: 0.1.0
    repository: "file://../service-1"
  - name: service-2
    version: 0.1.0
    repository: "file://../service-2"